# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  # Use the GRUB 2 boot loader.
  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  # Define on which hard drive you want to install Grub.
  boot.loader.grub.device = "/dev/sda";


  boot.initrd.luks.devices = [
    { name = "root";
      device = "/dev/sda6";
    }
  ];
  boot.initrd.luks.cryptoModules = [ "aes" "sha1" ];
  

  boot.initrd.availableKernelModules = [ "xhci_hcd" "ehci_pci" "ahci" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [
    "acpi_backlight=vendor"
    "video.use_native_backlight=1" 
  ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/" = { device = "/dev/mapper/root"; fsType = "btrfs"; };
    "/boot" = { device = "/dev/sda5"; fsType = "ext2"; };
  };

  swapDevices = [ ];

  nix.maxJobs = 4;
}
